// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePlayerItem = "player_items"

// PlayerItem mapped from table <player_items>
type PlayerItem struct {
	PlayerID  int32 `gorm:"column:playerID;primaryKey" json:"playerID"`
	ItemID    int32 `gorm:"column:itemID;primaryKey" json:"itemID"`
	ItemCount int32 `gorm:"column:item_count" json:"item_count"`
}

// TableName PlayerItem's table name
func (*PlayerItem) TableName() string {
	return TableNamePlayerItem
}
