// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePlayerSkill = "player_skills"

// PlayerSkill mapped from table <player_skills>
type PlayerSkill struct {
	PlayerID int32 `gorm:"column:playerID;primaryKey" json:"playerID"`
	SkillID  int32 `gorm:"column:skillID;primaryKey" json:"skillID"`
	Level    int32 `gorm:"column:level;default:1" json:"level"`
}

// TableName PlayerSkill's table name
func (*PlayerSkill) TableName() string {
	return TableNamePlayerSkill
}
