// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePlayer = "players"

// Player mapped from table <players>
type Player struct {
	PlayerID  int32     `gorm:"column:playerID;primaryKey;autoIncrement:true" json:"playerID"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Level     int32     `gorm:"column:level;default:1" json:"level"`
	Exp       int64     `gorm:"column:exp" json:"exp"`
	Gold      int64     `gorm:"column:gold" json:"gold"`
	LastLogin time.Time `gorm:"column:last_login;default:CURRENT_TIMESTAMP" json:"last_login"`
}

// TableName Player's table name
func (*Player) TableName() string {
	return TableNamePlayer
}
