// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePlayerAchievement = "player_achievements"

// PlayerAchievement mapped from table <player_achievements>
type PlayerAchievement struct {
	PlayerID      int32 `gorm:"column:playerID;primaryKey" json:"playerID"`
	AchievementID int32 `gorm:"column:achievementID;primaryKey" json:"achievementID"`
	AchievedAt    int64 `gorm:"column:achieved_at;default:CURRENT_TIMESTAMP" json:"achieved_at"`
}

// TableName PlayerAchievement's table name
func (*PlayerAchievement) TableName() string {
	return TableNamePlayerAchievement
}
