server:
  addr: 0.0.0.0:9090
  readTimeOut: 3s
  writeTimeOut: 3s
  idleTimeOut: 100s
mysql:
  - instance: default
    dsn: root:1234@tcp(127.0.0.1:3306)/mall?charset=utf8mb4&loc=Local&parseTime=True&timeout=3s
    trace_log: true
    slow_threshold: 100
redis:
  addr: 127.0.0.1:6379
  dialTimeOut: 100
  readTimeOut: 100
  writeTimeOut: 100
logger:
  logFile: log_files/mall.log
  logLevel: debug