// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Lu271/server-zys/internal/store/model"
)

func newPlayerItem(db *gorm.DB) playerItem {
	_playerItem := playerItem{}

	_playerItem.playerItemDo.UseDB(db)
	_playerItem.playerItemDo.UseModel(&model.PlayerItem{})

	tableName := _playerItem.playerItemDo.TableName()
	_playerItem.ALL = field.NewAsterisk(tableName)
	_playerItem.PlayerID = field.NewInt32(tableName, "playerID")
	_playerItem.ItemID = field.NewInt32(tableName, "itemID")
	_playerItem.ItemCount = field.NewInt32(tableName, "item_count")

	_playerItem.fillFieldMap()

	return _playerItem
}

type playerItem struct {
	playerItemDo playerItemDo

	ALL       field.Asterisk
	PlayerID  field.Int32
	ItemID    field.Int32
	ItemCount field.Int32

	fieldMap map[string]field.Expr
}

func (p playerItem) Table(newTableName string) *playerItem {
	p.playerItemDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p playerItem) As(alias string) *playerItem {
	p.playerItemDo.DO = *(p.playerItemDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *playerItem) updateTableName(table string) *playerItem {
	p.ALL = field.NewAsterisk(table)
	p.PlayerID = field.NewInt32(table, "playerID")
	p.ItemID = field.NewInt32(table, "itemID")
	p.ItemCount = field.NewInt32(table, "item_count")

	p.fillFieldMap()

	return p
}

func (p *playerItem) WithContext(ctx context.Context) *playerItemDo {
	return p.playerItemDo.WithContext(ctx)
}

func (p playerItem) TableName() string { return p.playerItemDo.TableName() }

func (p playerItem) Alias() string { return p.playerItemDo.Alias() }

func (p *playerItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *playerItem) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["playerID"] = p.PlayerID
	p.fieldMap["itemID"] = p.ItemID
	p.fieldMap["item_count"] = p.ItemCount
}

func (p playerItem) clone(db *gorm.DB) playerItem {
	p.playerItemDo.ReplaceDB(db)
	return p
}

type playerItemDo struct{ gen.DO }

func (p playerItemDo) Debug() *playerItemDo {
	return p.withDO(p.DO.Debug())
}

func (p playerItemDo) WithContext(ctx context.Context) *playerItemDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p playerItemDo) ReadDB() *playerItemDo {
	return p.Clauses(dbresolver.Read)
}

func (p playerItemDo) WriteDB() *playerItemDo {
	return p.Clauses(dbresolver.Write)
}

func (p playerItemDo) Clauses(conds ...clause.Expression) *playerItemDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p playerItemDo) Returning(value interface{}, columns ...string) *playerItemDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p playerItemDo) Not(conds ...gen.Condition) *playerItemDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p playerItemDo) Or(conds ...gen.Condition) *playerItemDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p playerItemDo) Select(conds ...field.Expr) *playerItemDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p playerItemDo) Where(conds ...gen.Condition) *playerItemDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p playerItemDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *playerItemDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p playerItemDo) Order(conds ...field.Expr) *playerItemDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p playerItemDo) Distinct(cols ...field.Expr) *playerItemDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p playerItemDo) Omit(cols ...field.Expr) *playerItemDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p playerItemDo) Join(table schema.Tabler, on ...field.Expr) *playerItemDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p playerItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) *playerItemDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p playerItemDo) RightJoin(table schema.Tabler, on ...field.Expr) *playerItemDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p playerItemDo) Group(cols ...field.Expr) *playerItemDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p playerItemDo) Having(conds ...gen.Condition) *playerItemDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p playerItemDo) Limit(limit int) *playerItemDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p playerItemDo) Offset(offset int) *playerItemDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p playerItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *playerItemDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p playerItemDo) Unscoped() *playerItemDo {
	return p.withDO(p.DO.Unscoped())
}

func (p playerItemDo) Create(values ...*model.PlayerItem) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p playerItemDo) CreateInBatches(values []*model.PlayerItem, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p playerItemDo) Save(values ...*model.PlayerItem) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p playerItemDo) First() (*model.PlayerItem, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlayerItem), nil
	}
}

func (p playerItemDo) Take() (*model.PlayerItem, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlayerItem), nil
	}
}

func (p playerItemDo) Last() (*model.PlayerItem, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlayerItem), nil
	}
}

func (p playerItemDo) Find() ([]*model.PlayerItem, error) {
	result, err := p.DO.Find()
	return result.([]*model.PlayerItem), err
}

func (p playerItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PlayerItem, err error) {
	buf := make([]*model.PlayerItem, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p playerItemDo) FindInBatches(result *[]*model.PlayerItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p playerItemDo) Attrs(attrs ...field.AssignExpr) *playerItemDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p playerItemDo) Assign(attrs ...field.AssignExpr) *playerItemDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p playerItemDo) Joins(fields ...field.RelationField) *playerItemDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p playerItemDo) Preload(fields ...field.RelationField) *playerItemDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p playerItemDo) FirstOrInit() (*model.PlayerItem, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlayerItem), nil
	}
}

func (p playerItemDo) FirstOrCreate() (*model.PlayerItem, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlayerItem), nil
	}
}

func (p playerItemDo) FindByPage(offset int, limit int) (result []*model.PlayerItem, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p playerItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p playerItemDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p playerItemDo) Delete(models ...*model.PlayerItem) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *playerItemDo) withDO(do gen.Dao) *playerItemDo {
	p.DO = *do.(*gen.DO)
	return p
}
