// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Lu271/server-zys/internal/store/model"
)

func newPlayerSkill(db *gorm.DB) playerSkill {
	_playerSkill := playerSkill{}

	_playerSkill.playerSkillDo.UseDB(db)
	_playerSkill.playerSkillDo.UseModel(&model.PlayerSkill{})

	tableName := _playerSkill.playerSkillDo.TableName()
	_playerSkill.ALL = field.NewAsterisk(tableName)
	_playerSkill.PlayerID = field.NewInt32(tableName, "playerID")
	_playerSkill.SkillID = field.NewInt32(tableName, "skillID")
	_playerSkill.Level = field.NewInt32(tableName, "level")

	_playerSkill.fillFieldMap()

	return _playerSkill
}

type playerSkill struct {
	playerSkillDo playerSkillDo

	ALL      field.Asterisk
	PlayerID field.Int32
	SkillID  field.Int32
	Level    field.Int32

	fieldMap map[string]field.Expr
}

func (p playerSkill) Table(newTableName string) *playerSkill {
	p.playerSkillDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p playerSkill) As(alias string) *playerSkill {
	p.playerSkillDo.DO = *(p.playerSkillDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *playerSkill) updateTableName(table string) *playerSkill {
	p.ALL = field.NewAsterisk(table)
	p.PlayerID = field.NewInt32(table, "playerID")
	p.SkillID = field.NewInt32(table, "skillID")
	p.Level = field.NewInt32(table, "level")

	p.fillFieldMap()

	return p
}

func (p *playerSkill) WithContext(ctx context.Context) *playerSkillDo {
	return p.playerSkillDo.WithContext(ctx)
}

func (p playerSkill) TableName() string { return p.playerSkillDo.TableName() }

func (p playerSkill) Alias() string { return p.playerSkillDo.Alias() }

func (p *playerSkill) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *playerSkill) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["playerID"] = p.PlayerID
	p.fieldMap["skillID"] = p.SkillID
	p.fieldMap["level"] = p.Level
}

func (p playerSkill) clone(db *gorm.DB) playerSkill {
	p.playerSkillDo.ReplaceDB(db)
	return p
}

type playerSkillDo struct{ gen.DO }

func (p playerSkillDo) Debug() *playerSkillDo {
	return p.withDO(p.DO.Debug())
}

func (p playerSkillDo) WithContext(ctx context.Context) *playerSkillDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p playerSkillDo) ReadDB() *playerSkillDo {
	return p.Clauses(dbresolver.Read)
}

func (p playerSkillDo) WriteDB() *playerSkillDo {
	return p.Clauses(dbresolver.Write)
}

func (p playerSkillDo) Clauses(conds ...clause.Expression) *playerSkillDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p playerSkillDo) Returning(value interface{}, columns ...string) *playerSkillDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p playerSkillDo) Not(conds ...gen.Condition) *playerSkillDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p playerSkillDo) Or(conds ...gen.Condition) *playerSkillDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p playerSkillDo) Select(conds ...field.Expr) *playerSkillDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p playerSkillDo) Where(conds ...gen.Condition) *playerSkillDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p playerSkillDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *playerSkillDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p playerSkillDo) Order(conds ...field.Expr) *playerSkillDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p playerSkillDo) Distinct(cols ...field.Expr) *playerSkillDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p playerSkillDo) Omit(cols ...field.Expr) *playerSkillDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p playerSkillDo) Join(table schema.Tabler, on ...field.Expr) *playerSkillDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p playerSkillDo) LeftJoin(table schema.Tabler, on ...field.Expr) *playerSkillDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p playerSkillDo) RightJoin(table schema.Tabler, on ...field.Expr) *playerSkillDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p playerSkillDo) Group(cols ...field.Expr) *playerSkillDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p playerSkillDo) Having(conds ...gen.Condition) *playerSkillDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p playerSkillDo) Limit(limit int) *playerSkillDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p playerSkillDo) Offset(offset int) *playerSkillDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p playerSkillDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *playerSkillDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p playerSkillDo) Unscoped() *playerSkillDo {
	return p.withDO(p.DO.Unscoped())
}

func (p playerSkillDo) Create(values ...*model.PlayerSkill) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p playerSkillDo) CreateInBatches(values []*model.PlayerSkill, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p playerSkillDo) Save(values ...*model.PlayerSkill) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p playerSkillDo) First() (*model.PlayerSkill, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlayerSkill), nil
	}
}

func (p playerSkillDo) Take() (*model.PlayerSkill, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlayerSkill), nil
	}
}

func (p playerSkillDo) Last() (*model.PlayerSkill, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlayerSkill), nil
	}
}

func (p playerSkillDo) Find() ([]*model.PlayerSkill, error) {
	result, err := p.DO.Find()
	return result.([]*model.PlayerSkill), err
}

func (p playerSkillDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PlayerSkill, err error) {
	buf := make([]*model.PlayerSkill, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p playerSkillDo) FindInBatches(result *[]*model.PlayerSkill, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p playerSkillDo) Attrs(attrs ...field.AssignExpr) *playerSkillDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p playerSkillDo) Assign(attrs ...field.AssignExpr) *playerSkillDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p playerSkillDo) Joins(fields ...field.RelationField) *playerSkillDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p playerSkillDo) Preload(fields ...field.RelationField) *playerSkillDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p playerSkillDo) FirstOrInit() (*model.PlayerSkill, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlayerSkill), nil
	}
}

func (p playerSkillDo) FirstOrCreate() (*model.PlayerSkill, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlayerSkill), nil
	}
}

func (p playerSkillDo) FindByPage(offset int, limit int) (result []*model.PlayerSkill, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p playerSkillDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p playerSkillDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p playerSkillDo) Delete(models ...*model.PlayerSkill) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *playerSkillDo) withDO(do gen.Dao) *playerSkillDo {
	p.DO = *do.(*gen.DO)
	return p
}
